### ISSUE TITLE
Dimensions of rectangular 90deg key caps are incorrect

### ISSUE THREAD

**Issue by JustCallMeUni** [kiswitch/kiswitch#52]
### For instance:
Choc key caps are 18x17mm
So you would expect 2.00u 90deg would be 18x34mm, when in reality it is 17x36.
As a result of this the key-cap outline for the 2.00u 90deg does not align with the other ones

**Comment by perigoso** [comment]
After looking into it, it looks like expected, I either resolved the issue by accident or it was never present
