### ISSUE TITLE
Difference between SW_Hotswap_Kailh_MX and SW_Hotswap_Kailh_MX_plated?

### ISSUE THREAD

**Issue by HaoboGu** [kiswitch/kiswitch#63]
Hello, I'm wondering what's the difference between SW_Hotswap_Kailh_MX and SW_Hotswap_Kailh_MX_plated? and which one should I use for PCB?

**Comment by perigoso** [comment]
Hello, 

the plated variant has plating around the hot swap socket holes, while the regular doesn't, one could say it improves the strength of the socket, as in, it's harder to rip from the board, but that is not proven

Which you use is totally up to you

**Comment by HaoboGu** [comment]
@perigoso thanks for the explanation!
